# ClusterEye Agent - Windows Installer
# Windows counterpart of the Linux install.sh. Designed for UI-driven bootstrap install.
#
# Usage (command generated by the UI):
#   & ([scriptblock]::Create((irm https://archive.clustereye.com/install.ps1))) `
#       -ApiUrl 10.0.0.1:50051 -RegistrationToken eyJ... [-Tls] [-SkipVerify]

param(
    [string]$Platform = "mssql",
    [string]$ApiUrl = "",
    [string]$RegistrationToken = "",
    [switch]$Tls,
    [switch]$SkipVerify,
    [string]$InstallDir = "C:\Program Files\ClusterEyeAgent",
    # Offline install: path to a pre-downloaded clustereye-agent.exe. When set,
    # the binary is copied locally instead of downloaded from the archive.
    [string]$LocalBinary = "",
    # Version-pinned, verified install. The ClusterEye UI reads these from the
    # release manifest and puts them in the command; when they are present the
    # zip package is installed instead of the bare exe, and nothing lands in
    # $InstallDir until its digest matches.
    [string]$PackageUrl = "",
    [string]$LocalPackage = "",
    [string]$Sha256 = "",
    [string]$Version = ""
)

$ErrorActionPreference = "Stop"

# Windows PowerShell 5.1 does not enable TLS 1.2 by default; the archive is
# served over GitHub Pages (TLS 1.2+). Set it once, up front.
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12

$ServiceName = "ClusterEyeAgent"
# Latest agent version is resolved at runtime from the archive release manifest
# (see "Download agent binary" below) - no manual version bump needed.
$ReleasesUrl = "https://archive.clustereye.com/releases.json"

function Write-Step($msg) { Write-Host "`n==> $msg" -ForegroundColor Yellow }
function Write-Ok($msg)   { Write-Host "    $msg" -ForegroundColor Green }
function Write-Fail($msg) { Write-Host "ERROR: $msg" -ForegroundColor Red }

# --- Administrator check ---
$isAdmin = ([Security.Principal.WindowsPrincipal] `
    [Security.Principal.WindowsIdentity]::GetCurrent()
).IsInRole([Security.Principal.WindowsBuiltinRole]::Administrator)
if (-not $isAdmin) {
    Write-Fail "This script must be run as Administrator."
    exit 1
}

# --- Parameter validation ---
if ([string]::IsNullOrWhiteSpace($ApiUrl) -or [string]::IsNullOrWhiteSpace($RegistrationToken)) {
    Write-Fail "-ApiUrl and -RegistrationToken are required."
    exit 1
}

# Append the default gRPC port (50051) if no port is given.
if ($ApiUrl -notmatch ":\d+$") {
    $GrpcAddress = "${ApiUrl}:50051"
} else {
    $GrpcAddress = $ApiUrl
}

# Note: variable names must NOT case-collide with the [switch] params above
# ($Tls / $SkipVerify) - PowerShell variables are case-insensitive, so a name
# like $skipVerify would overwrite the $SkipVerify switch and break binding.
$tlsValue        = if ($Tls) { "true" } else { "false" }
$skipVerifyValue = if ($SkipVerify) { "true" } else { "false" }
$hostName        = $env:COMPUTERNAME

Write-Host "ClusterEye Agent installation starting..." -ForegroundColor Yellow
Write-Host "Platform: $Platform"
Write-Host "Install directory: $InstallDir"
Write-Host "API address: $GrpcAddress (TLS: $tlsValue)"

# --- 1. Install directory ---
Write-Step "1. Preparing install directory..."
New-Item -ItemType Directory -Force -Path $InstallDir | Out-Null
New-Item -ItemType Directory -Force -Path (Join-Path $InstallDir "logs") | Out-Null
Write-Ok "$InstallDir ready"

$ExePath = Join-Path $InstallDir "clustereye-agent.exe"

# --- 2. Stop existing service (idempotent reinstall) ---
$existing = Get-Service -Name $ServiceName -ErrorAction SilentlyContinue
if ($existing -and $existing.Status -eq "Running") {
    Write-Step "Stopping existing service..."
    Stop-Service -Name $ServiceName -Force -ErrorAction SilentlyContinue
    Start-Sleep -Seconds 2
}

# --- 3. Provide agent binary (offline: copy local file; online: download) ---
# A package source without a digest would make disabling verification a matter
# of dropping one flag, so the two are required together.
if (($PackageUrl -or $LocalPackage) -and -not $Sha256) {
    Write-Fail "-PackageUrl/-LocalPackage must be used together with -Sha256"
    exit 1
}
if ($PackageUrl -and $LocalPackage) {
    Write-Fail "-PackageUrl and -LocalPackage cannot be used together"
    exit 1
}

# Assert-Sha256 stops the install on a mismatch. It deletes the file and leaves
# any running agent untouched: a failed install must not be a broken one.
function Assert-Sha256([string]$Path, [string]$Expected) {
    $actual = (Get-FileHash -Algorithm SHA256 -Path $Path).Hash
    if ($actual -ine $Expected) {
        # Delete first, report second. If reporting ever grows a side effect
        # that aborts, the unverified file must already be gone.
        Remove-Item -Path $Path -Force -ErrorAction SilentlyContinue
        Write-Fail "Integrity check FAILED - install aborted."
        Write-Host "    expected: $($Expected.ToLower())"
        Write-Host "    actual  : $($actual.ToLower())"
        exit 1
    }
    Write-Ok "SHA-256 verified"
}

if ($PackageUrl -or $LocalPackage) {
    # Package mode. The zip carries ClusterEyeAgentUpdater.exe alongside the
    # agent; installing only the bare exe left every agent unable to self-update,
    # because the updater is looked up in the install dir at update time.
    $stage = Join-Path $env:TEMP ("ce-agent-" + [guid]::NewGuid().ToString("N"))
    New-Item -ItemType Directory -Path $stage -Force | Out-Null
    $pkg = Join-Path $stage "agent-package.zip"
    try {
        if ($LocalPackage) {
            Write-Step "2. Verifying local package: $LocalPackage"
            if (-not (Test-Path $LocalPackage)) { Write-Fail "Local package not found: $LocalPackage"; exit 1 }
            Copy-Item -Path $LocalPackage -Destination $pkg -Force
        } else {
            Write-Step "2. Downloading agent package..."
            if ($Version) { Write-Host "    Version: $Version" }
            Write-Host "    URL: $PackageUrl"
            try {
                Invoke-WebRequest -Uri $PackageUrl -OutFile $pkg -UseBasicParsing
            } catch {
                Write-Fail "Failed to download package: $($_.Exception.Message)"
                Write-Host "    This command is pinned to a version that may have been pruned from the archive."
                Write-Host "    Regenerate the install command from the ClusterEye UI."
                exit 1
            }
        }

        # Before Expand-Archive: extracting an archive is itself an attack surface.
        Assert-Sha256 -Path $pkg -Expected $Sha256

        Write-Step "    Extracting package..."
        Expand-Archive -Path $pkg -DestinationPath $InstallDir -Force
        if (-not (Test-Path $ExePath)) {
            Write-Fail "Package did not contain clustereye-agent.exe"
            exit 1
        }
        Write-Ok "Agent package installed$(if ($Version) { " ($Version)" })"
    } finally {
        Remove-Item -Path $stage -Recurse -Force -ErrorAction SilentlyContinue
    }
} elseif ($LocalBinary) {
    Write-Step "2. Copying local agent binary..."
    if (-not (Test-Path $LocalBinary)) {
        Write-Fail "Local binary not found: $LocalBinary"
        exit 1
    }
    Copy-Item -Path $LocalBinary -Destination $ExePath -Force
    # Verify when a digest was supplied — for an air-gapped install this is the
    # only check the operator gets.
    if ($Sha256) { Assert-Sha256 -Path $ExePath -Expected $Sha256 }
    Write-Ok "clustereye-agent.exe copied from $LocalBinary"
} else {
    Write-Step "2. Downloading agent binary..."
    try {
        $releases = Invoke-RestMethod -Uri $ReleasesUrl -UseBasicParsing
        $AgentVersion = ($releases.agent.releases | Where-Object { $_.latest } | Select-Object -First 1).version
    } catch {
        Write-Fail "Failed to read release manifest ($ReleasesUrl): $($_.Exception.Message)"
        exit 1
    }
    if ([string]::IsNullOrWhiteSpace($AgentVersion)) {
        Write-Fail "Could not determine the latest agent version from releases.json"
        exit 1
    }
    $ExeUrl = "https://archive.clustereye.com/downloads/agent/$AgentVersion/clustereye-agent.exe"
    Write-Host "    Version: $AgentVersion"
    Write-Host "    URL: $ExeUrl"
    try {
        Invoke-WebRequest -Uri $ExeUrl -OutFile $ExePath -UseBasicParsing
    } catch {
        Write-Fail "Failed to download binary: $($_.Exception.Message)"
        exit 1
    }
    Write-Ok "clustereye-agent.exe downloaded ($AgentVersion)"
    Write-Host "    Warning: version not pinned, integrity not verified."
    Write-Host "    Generate the command from the ClusterEye UI for a verified install."
}

# --- 4. Write agent.yml ---
Write-Step "3. Writing configuration file..."
$AgentYml = @"
name: $hostName
grpc:
  server_address: $GrpcAddress
  tls_enabled: $tlsValue
  insecure_skip_verify: $skipVerifyValue
auth:
  registration_token: $RegistrationToken
logging:
  level: "INFO"
  use_eventlog: true
  use_filelog: true
security:
  enabled: true
  scan_interval_hours: 6
"@
$ymlPath = Join-Path $InstallDir "agent.yml"
# UTF-8 without BOM - the Go YAML parser does not like a BOM.
[IO.File]::WriteAllText($ymlPath, $AgentYml, (New-Object Text.UTF8Encoding $false))
Write-Ok "agent.yml written (database connection details set later from the UI)"

# --- 5. Install and start the Windows service ---
Write-Step "4. Installing Windows service..."
if ($existing) {
    & $ExePath -service uninstall 2>$null
    Start-Sleep -Seconds 2
}
& $ExePath -platform $Platform -service install
if ($LASTEXITCODE -ne 0) {
    Write-Fail "Service installation failed."
    exit 1
}

# Auto-restart on failure: after a config push the agent exits with a non-zero
# code on purpose; the service manager must bring it back up. Without this the
# service stays Stopped after every database configuration change.
& sc.exe failure $ServiceName reset= 86400 actions= restart/5000/restart/5000/restart/5000 | Out-Null

& $ExePath -platform $Platform -service start
if ($LASTEXITCODE -ne 0) {
    Write-Fail "Service failed to start."
    exit 1
}

Write-Host "`nInstallation complete and agent started!" -ForegroundColor Green
Write-Host "The agent is connecting to the ClusterEye API; it will appear in the UI shortly."
Write-Host "Service status:  Get-Service $ServiceName"
Write-Host "Logs:            $InstallDir\logs"
